### ISSUE TITLE
Unable to install "wtt pack 'n' strap"

### ISSUE THREAD

**Issue by Muramas** [SchraderR/sp-tarkov-client#106]
I attempted to install the mod which says it installed it but when I reboot the SP-EFT manager it doesn't show up and lets me install again.
Does not show up in list.
Running v0.2.10

https://hub.sp-tarkov.com/files/file/1790-wtt-pack-n-strap/

**Comment by SchraderR** [comment]
Its an issue with the current implementation of rar archives. This mod is a "happy path mod" (user/mod and plugin directory) but the path is not implemented.

app/events/file-unzip.event.ts -> handleRarArchive

**Comment by SchraderR** [comment]
- [ ] Fix unzip event
- [ ] Fix name mapping
