### ISSUE TITLE
[Suggestion] Filter search 

### ISSUE THREAD

**Issue by Muramas** [SchraderR/sp-tarkov-client#110]
First off, I think this app is the best way right now to search and install mods and it should be part of the base SPT. 

It would be nice in the searches that we can filter out things like 
-Version / Current version (see only versions you are looking for)
-Tags (If this information is grabbed from https://hub.sp-tarkov.com/ each mod had tags) 

The search right now does a basic title search and won't find anything that doesn't have the thing you are looking for specifically in the title.

**Comment by SchraderR** [comment]
- [ ] get scrollableDropdownMenu
- [ ] save config / settings
- [ ] match data-label-id and span (only text)
- [ ] adding ui to select the id (append it to the search)
- [ ] testing
