### ISSUE TITLE
Adding better SPT version filter

### ISSUE THREAD

**Issue by Peron4TheWin** [SchraderR/sp-tarkov-client#173]
This is a super great and intuitive tool

I'll love to be able to filter SPT versions better, for example "Greater or equal than spt 3.9.0" because a 3.9.0 mod can run in 3.9.4 and so on
Thanks you for doing this tool

**Comment by SchraderR** [comment]
Is this feature on the current hub? If not, i am not able to implement this due to the limiation of WoltLab Hub.

**Comment by SchraderR** [comment]
Closed until feedback

**Comment by Peron4TheWin** [comment]
No, its not a Hub feature, didn't know about the limitations of Woltlab
Couldn't be made client side? You made the general request for all file and check them client side to see if they are greater than 3.9.0 for example?
